import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="pt" className={chivoMono.variable}> 
//       <body className="antialiased">
//         {children}
//       </body>
//     </html>
//   )
// }
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt">
      <body className="antialiased bg-background">
        <Navbar />
        <div className="mx-auto page-x-padding pt-6 pb-32">
          {children}

        </div>

        <Footer />
      </body>
    </html>
  );
}