import type { Metadata } from "next";
import { Chivo_Mono } from 'next/font/google';
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./globals.css";

// const chivoMono = Chivo_Mono({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-chivo-mono', // Criamos uma variável CSS
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="pt" className={chivoMono.variable}> 
//       <body className="antialiased">
//         {children}
//       </body>
//     </html>
//   )
// }
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt">
      <body className="antialiased bg-background">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}