export interface Project {
  id: string;
  title: string;
  year: string;
  category: string;
  imageUrl: string;
  slug: string;
  director: string;
  dop: string;
  production: string;
  heroImage: string;
  gallery: string[];
  // Aceita "top", "bottom", "center", "25%", "80%", ou qualquer outra string de posição
  heroPosition?: string; 
}

export const projects: Project[] = [
  {
      id: "1",
      title: "Mulheres, Às Armas",
      year: "2025",
      category: "narrative",
      imageUrl: "/images/narrative/MulheresAsArmas/0MulheresAsArmas.jpeg",
      slug: "mulheres-as-armas",
      director: "Patrícia Sequeira",
      dop: "Hugo Azevedo",
      production: "Santa Rita Filmes & TVI",
      heroImage: "/images/home/MulheresAsArmas.jpg",
      gallery: Array.from({ length: 33 }, (_, i) => `/images/narrative/MulheresAsArmas/${i}MulheresAsArmas.jpeg`),
  },
  {
      id: "2",
      title: "As If The World Had No West",
      year: "2025",
      category: "narrative",
      imageUrl: "/images/narrative/AsIfTheWorldHadNoWest/0AsIfTheWorldHadNoWest.jpg",
      slug: "AsIfTheWorld",
      director: "Mónica de Miranda",
      dop: "Mónica de Miranda",
      production: "Kintop",
      heroImage: "", 
      // Altera o length para 17 para apanhar desde o 0 até ao 33
      gallery: Array.from({ length: 17 }, (_, i) => `/images/narrative/AsIfTheWorldHadNoWest/${i}AsIfTheWorldHadNoWest.jpg`),
  },
  {
      id: "3",
      title: "Sonido: Ivans & Tobis",
      year: "2023",
      category: "narrative",
      imageUrl: "/images/narrative/SonidoIvans&Tobis/0Sonido.jpg",
      slug: "sonido",
      director: "Diogo Baldaia",
      dop: "Manuel Pinho Braga",
      production: "O Som e a Fúria",
      heroImage: "/images/home/MulheresAsArmas.jpg",
      gallery: Array.from({ length: 12 }, (_, i) => `/images/narrative/SonidoIvans&Tobis/${i}Sonido.jpg`),
  },
  {
      id: "4",
      title: "Índia",
      year: "2022",
      category: "narrative",
      imageUrl: "/images/narrative/India/0India.jpg",
      slug: "india",
      director: "Telmo Churro",
      dop: "Mário Castanheira",
      production: "O Som e a Fúria",
      heroImage: "/images/home/India.jpg",
      gallery: Array.from({ length: 22 }, (_, i) => `/images/narrative/India/${i}India.jpg`),
       heroPosition: "20%",
  },
  {
      id: "5",
      title: "Claridade",
      year: "2024",
      category: "narrative",
      imageUrl: "/images/narrative/Claridade/0Claridade.jpeg",
      slug: "claridade",
      director: "Mariana Santana",
      dop: "Leonardo Simões e Mariana Santana",
      production: "Blenda",
      heroImage: "/images/home/Claridade.jpg",
      gallery: Array.from({ length: 18 }, (_, i) => `/images/narrative/Claridade/${i}Claridade.jpeg`),
  },
  {
      id: "6",
      title: "Ancoradouro Do Tempo",
      year: "2024",
      category: "narrative",
      imageUrl: "/images/narrative/Ancoradouro/1Ancoradouro.jpeg",
      slug: "ancoradouro-do-tempo",
      director: "Sol de Carvalho",
      dop: "André Guiomar",
      production: "Real Ficção e Promarte",
      heroImage: "/images/home/AncoradouroDoTempo",
      gallery: Array.from({ length: 33 }, (_, i) => `/images/narrative/Ancoradouro/${i + 1}Ancoradouro.jpeg`),
  },
  {
      id: "7",
      title: "A Moeda-Viva",
      year: "2024",
      category: "narrative",
      imageUrl: "/images/narrative/MoedaViva/0MoedaViva.jpeg",
      slug: "a-moeda-viva",
      director: "Pedro Paiva",
      dop: "Leonardo Simões",
      production: "Água Pé, Manuel Rocha da Silva e Optec",
      heroImage: "/images/home/MulheresAsArmas.jpg",
      gallery: Array.from({ length: 7 }, (_, i) => `/images/narrative/MoedaViva/${i}MoedaViva.jpeg`),
      heroPosition: "20%",
  },
  {
      id: "8",
      title: "O Rio E Seu Labirinto",
      year: "2023",
      category: "narrative",
      imageUrl: "/images/narrative/ORioESeuLabirinto/0ORioESeuLabirinto.jpg",
      slug: "o-rio-e-seu-labirinto",
      director: "Ian Capillé",
      dop: "Manuel Pinho Braga",
      production: "Ian Capillé, Manuel Rocha da Silva, Gabriela Giffoni e Bruno Abib",
      heroImage: "/images/home/MulheresAsArmas", 
      gallery: Array.from({ length: 9 }, (_, i) => `/images/narrative/ORioESeuLabirinto/${i}ORioESeuLabirinto.jpg`),
  },
  {
      id: "9",
      title: "O Natal Do Bruno Aleixo",
      year: "2023",
      category: "narrative",
      imageUrl: "/images/narrative/ONBA/0ONBA.jpg",
      slug: "o-natal-do-bruno-aleixo",
      director: "João Moreira e Pedro Santo",
      dop: "Francisco Carvalho",
      production: "O Som e a Fúria",
       heroImage: "/images/home/ONatalDoBrunoAleixo", 
     
      gallery: Array.from({ length: 4 }, (_, i) => `/images/narrative/ONBA/${i}ONBA.jpg`),
  },
  {
      id: "10",
      title: "O Clube - Season 3",
      year: "2023",
      category: "narrative",
      imageUrl: "/images/narrative/OClube/0OClube.jpeg",
      slug: "o-clube-season-3",
      director: "Patrícia Sequeira",
      dop: "Paulo Castilho",
      production: "Santa Rita Filmes",
      heroImage: "/images/home/OClube.jpg",
      gallery: Array.from({ length: 5 }, (_, i) => `/images/narrative/OClube/${i}OClube.jpeg`),
  },
  {
      id: "11",
      title: "O Trio Em Mi Bemol",
      year: "2023",
      category: "narrative",
      imageUrl: "/images/narrative/OTrioEmMiBemol/0OTrioEmMiBemol.jpg",
      slug: "o-trio-em-mi-bemol",
      director: "Rita Azevedo Gomes",
      dop: "Jorge Quintela",
      production: "Basilisco Filmes",
      heroImage: "/images/home/OTrioEmMiBemol.jpg",
      gallery: Array.from({ length: 11 }, (_, i) => `/images/narrative/OTrioEmMiBemol/${i}OTrioEmMiBemol.jpg`),
  },
  {
      id: "11",
      title: "O Trio Em Mi Bemol",
      year: "2023",
      category: "documentary",
      imageUrl: "/images/narrative/OTrioEmMiBemol/0OTrioEmMiBemol.jpg",
      slug: "o-trio-em-mi-bemol",
      director: "Rita Azevedo Gomes",
      dop: "Jorge Quintela",
      production: "Basilisco Filmes",
      heroImage: "/images/home/OTrioEmMiBemol.jpg",
      gallery: Array.from({ length: 11 }, (_, i) => `/images/narrative/OTrioEmMiBemol/${i}OTrioEmMiBemol.jpg`),
  },
]
